# Generated by Django 2.0.7 on 2019-01-05 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade_for_subject',
            fields=[
                ('id_grade', models.AutoField(primary_key=True, serialize=False)),
                ('semestre', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')])),
                ('grade', models.IntegerField(choices=[(2, 'Не сдан'), (3, 'Удовлетворительно'), (4, 'Хорошо'), (5, 'Отлично'), (5, 'Зачет'), (2, 'Не зачет')])),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('students_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('FIO', models.CharField(help_text='Enter name of student', max_length=30)),
                ('contacts', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id_of_subject', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_subject', models.CharField(help_text='Subject is', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id_tutor', models.AutoField(primary_key=True, serialize=False)),
                ('FIO', models.CharField(help_text='Enter name of the tutor', max_length=30)),
                ('contacts', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='id_tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Tutor'),
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.ManyToManyField(to='catalog.Subject'),
        ),
        migrations.AddField(
            model_name='grade_for_subject',
            name='students_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Student'),
        ),
        migrations.AddField(
            model_name='grade_for_subject',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Subject'),
        ),
    ]
