# Generated by Django 2.0.7 on 2019-01-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='intrance_year',
            field=models.IntegerField(blank=True, default=2005, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name_of_subject',
            field=models.CharField(help_text='Subject is', max_length=50),
        ),
    ]
